class UbigeoPeru {
  static const List<String> departamentos = [
    'Lima',
    'Callao',
    'Arequipa',
    'Cusco',
    'La Libertad',
    'Piura',
    'Junín',
    'Puno',
    'Áncash',
    'Lambayeque',
    'Ica',
    'Loreto',
    'Cajamarca',
    'Tacna',
    'Moquegua',
    'Ucayali',
    'San Martín',
    'Huánuco',
    'Ayacucho',
    'Tumbes',
    'Amazonas',
    'Huancavelica',
    'Apurímac',
    'Pasco',
    'Madre de Dios',
  ];

  static const Map<String, List<String>> provinciasPorDepartamento = {
    'Lima': [
      'Lima',
      'Barranca',
      'Cajatambo',
      'Canta',
      'Cañete',
      'Huaral',
      'Huarochirí',
      'Huaura',
      'Oyón',
      'Yauyos',
    ],
    'Callao': ['Callao'],
    'Arequipa': [
      'Arequipa',
      'Camaná',
      'Caravelí',
      'Castilla',
      'Caylloma',
      'Condesuyos',
      'Islay',
      'La Unión',
    ],
    'La Libertad': [
      'Trujillo',
      'Ascope',
      'Bolívar',
      'Chepén',
      'Julcán',
      'Otuzco',
      'Pacasmayo',
      'Pataz',
      'Sánchez Carrión',
      'Santiago de Chuco',
      'Gran Chimú',
      'Virú',
    ],
    'Piura': [
      'Piura',
      'Ayabaca',
      'Huancabamba',
      'Morropón',
      'Paita',
      'Sullana',
      'Talara',
      'Sechura',
    ],
    'Cusco': [
      'Cusco',
      'Acomayo',
      'Anta',
      'Calca',
      'Canas',
      'Canchis',
      'Chumbivilcas',
      'Espinar',
      'La Convención',
      'Paruro',
      'Paucartambo',
      'Quispicanchi',
      'Urubamba',
    ],
    'Lambayeque': ['Chiclayo', 'Ferreñafe', 'Lambayeque'],
    'Junín': [
      'Huancayo',
      'Concepción',
      'Chanchamayo',
      'Jauja',
      'Junín',
      'Satipo',
      'Tarma',
      'Yauli',
      'Chupaca',
    ],
    'Ica': ['Ica', 'Chincha', 'Nazca', 'Palpa', 'Pisco'],
    'Áncash': ['Huaraz', 'Santa (Chimbote)', 'Casma', 'Huarmey', 'Caraz'],
  };

  static const List<String> distritosLima = [
    'Ancón',
    'Ate',
    'Barranco',
    'Breña',
    'Carabayllo',
    'Chaclacayo',
    'Chorrillos',
    'Cieneguilla',
    'Comas',
    'El Agustino',
    'Independencia',
    'Jesús María',
    'La Molina',
    'La Victoria',
    'Lima (Cercado)',
    'Lince',
    'Los Olivos',
    'Lurigancho-Chosica',
    'Lurín',
    'Magdalena del Mar',
    'Miraflores',
    'Pachacámac',
    'Pucusana',
    'Pueblo Libre',
    'Puente Piedra',
    'Punta Hermosa',
    'Punta Negra',
    'Rímac',
    'San Bartolo',
    'San Borja',
    'San Isidro',
    'San Juan de Lurigancho',
    'San Juan de Miraflores',
    'San Luis',
    'San Martín de Porres',
    'San Miguel',
    'Santa Anita',
    'Santa María del Mar',
    'Santa Rosa',
    'Santiago de Surco',
    'Surquillo',
    'Villa El Salvador',
    'Villa María del Triunfo',
  ];

  static const List<String> distritosCallao = [
    'Bellavista',
    'Callao (Cercado)',
    'Carmen de La Legua-Reynoso',
    'La Perla',
    'La Punta',
    'Mi Perú',
    'Ventanilla',
  ];

  static List<String> getProvincias(String? departamento) {
    if (departamento == null || departamento.isEmpty) {
      return provinciasPorDepartamento['Lima']!;
    }
    return provinciasPorDepartamento[departamento] ?? [departamento];
  }

  static List<String> getDistritos(String? departamento) {
    if (departamento == 'Callao') {
      return distritosCallao;
    }
    return distritosLima;
  }
}
